### ISSUE TITLE
[bug] dropdown selectors do not hide upon selection

### ISSUE THREAD

**Issue by petersonbrock** [associatedemployers/quartz#22]
works fine when manually entering class, but behaved weird when using computed property
/templates/components/input/quick-form-input

**Comment by petersonbrock** [comment]
![Screen Shot 2018-06-12 at 3.09.29 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59ee27aac0b55600122fb66f/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77256455f16b7191a37bf112224f5d565ecc3c4a4356bcbbd671f3e57862804e0eead26e5a7dce3c18afecd04dba03bf208a4e84b7e9d91ad2f42f67b6d5db1063474f4dcbed5727a19041c95df443e94e52ad123167e5702431.png)

**Comment by James1x0** [comment]
Closed via https://github.com/associatedemployers/quartz/pull/23
