### ISSUE TITLE
[Bug] Careers application finishes if exited

### ISSUE THREAD

**Issue by JavaLavaMT** [associatedemployers/quartz#51]
when entering an application and click "back to careers" and then go back in to the app to answer the questions, the system thinks the app is done and wont let you do anything

**Comment by JavaLavaMT** [comment]
![image](https://user-images.githubusercontent.com/25805625/53190391-bc45d280-35c6-11e9-9ea6-e5eb5c329e54.png)

**Comment by James1x0** [comment]
Good catch

**Comment by JavaLavaMT** [comment]
![image](https://user-images.githubusercontent.com/25805625/54847282-9255fd80-4ca3-11e9-94cb-51c835a942b0.png)
